services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: time_tracker
      MYSQL_USER: lmorival
      MYSQL_PASSWORD: leon
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  nodejs:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: lmorival
      DB_PASSWORD: leon
      DB_NAME: time_tracker
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
